# Generated by Django 4.2 on 2026-06-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediciones', '0005_device_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='token',
            field=models.CharField(help_text='Token de autenticación único para el dispositivo', max_length=512, unique=True, verbose_name='Token'),
        ),
    ]
