# Generated by Django 4.2 on 2026-03-21 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(help_text='Resumen o bajada de la actividad', verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('featured_image', models.CharField(blank=True, help_text='Ej: /img/fotos/mi-foto.jpg', max_length=255, verbose_name='Ruta a Imagen Destacada')),
                ('tags', models.CharField(blank=True, help_text='Separados por comas', max_length=255, verbose_name='Tags')),
                ('content', models.TextField(help_text='Cuerpo de la actividad en formato Markdown', verbose_name='Contenido Markdown')),
            ],
            options={
                'verbose_name': 'Actividad (Hugo)',
                'verbose_name_plural': 'Actividades (Hugo)',
            },
        ),
    ]
