# Generated by Django 4.2 on 2026-07-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hugo_edit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Resumen o bajada (opcional)', verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('featured_image', models.CharField(blank=True, help_text='Ej: /img/estudios/2023/imagen.png', max_length=255, verbose_name='Ruta a Imagen Destacada')),
                ('content', models.TextField(help_text='Cuerpo del estudio en formato Markdown', verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Estudio (Hugo)',
                'verbose_name_plural': 'Estudios (Hugo)',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(blank=True, help_text='Resumen o bajada (opcional)', verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('tags', models.CharField(blank=True, help_text='Separados por comas', max_length=255, verbose_name='Tags')),
                ('content', models.TextField(help_text='Cuerpo de la noticia en formato Markdown', verbose_name='Contenido')),
            ],
            options={
                'verbose_name': 'Noticia (Hugo)',
                'verbose_name_plural': 'Noticias (Hugo)',
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=models.TextField(help_text='Cuerpo de la actividad en formato Markdown', verbose_name='Contenido'),
        ),
    ]
